title: Zhaoyu's Blog
description: 技术 · 思考 · 生活
url: https://zhaoyul.github.io
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
