title: Zhaoyu's Blog
description: 这次，不一样了。持续记录 AI coding 的最佳实践。
url: https://zhaoyul.github.io
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll-seo-tag
